name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: KrrishSR4

          template: classic
          base: header, activity, community, repositories, metadata

          config_timezone: Asia/Kolkata

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used

          plugin_isocalendar: yes

          plugin_achievements: yes
          plugin_achievements_threshold: C

          plugin_followup: yes
          plugin_followup_sections: repositories

          plugin_lines: yes

          filename: github-metrics.svg

      - name: Push Metrics
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update github metrics"
